// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_mHeiVxgfHEPo-cKi06egLV2BiQ7Sxf4',
    appId: '1:177123739027:web:6df3cd13eaf5d615161466',
    messagingSenderId: '177123739027',
    projectId: 'flutter-cookbook-194ee',
    authDomain: 'flutter-cookbook-194ee.firebaseapp.com',
    storageBucket: 'flutter-cookbook-194ee.appspot.com',
    measurementId: 'G-YD6DVRB6CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDakmNeXtoiy-Z2HLBRkSWEwDDBGapB59I',
    appId: '1:177123739027:android:5ebd70001d4c594b161466',
    messagingSenderId: '177123739027',
    projectId: 'flutter-cookbook-194ee',
    storageBucket: 'flutter-cookbook-194ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOvYXNr7_nGj5PpHgz-sVmY-1Ot9BLkwo',
    appId: '1:177123739027:ios:0bdd63f57713de98161466',
    messagingSenderId: '177123739027',
    projectId: 'flutter-cookbook-194ee',
    storageBucket: 'flutter-cookbook-194ee.appspot.com',
    iosClientId: '177123739027-5603l75sd0n2b5af290en7os22r2o3i7.apps.googleusercontent.com',
    iosBundleId: 'it.lantran.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOvYXNr7_nGj5PpHgz-sVmY-1Ot9BLkwo',
    appId: '1:177123739027:ios:76dd12021ae5d24f161466',
    messagingSenderId: '177123739027',
    projectId: 'flutter-cookbook-194ee',
    storageBucket: 'flutter-cookbook-194ee.appspot.com',
    iosClientId: '177123739027-d5gsh3mkl0tk6ssfrqic9ge2vk6tqh52.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );
}
